version: '3.8'
    
services:
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./test_backend/:/usr/src/test_backend/
    ports:
      - "8000:8000"
