# Generated by Django 3.1 on 2020-08-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='url',
        ),
    ]
