# Generated by Django 3.1 on 2020-08-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0003_auto_20200814_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='files',
        ),
    ]
