# Generated by Django 3.1 on 2020-08-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0004_auto_20200814_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
