# Generated by Django 3.1 on 2020-08-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0006_auto_20200814_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, upload_to='static/'),
        ),
    ]
