# Generated by Django 3.1 on 2020-08-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0008_auto_20200815_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.CharField(default='height', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.CharField(default='width', max_length=300),
        ),
    ]
