# Generated by Django 3.1 on 2020-08-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0009_auto_20200815_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.ImageField(blank=True, height_field='height', upload_to='', width_field='width'),
        ),
    ]
